sseicss:
    resource: "@SSEICSSBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /console

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /console