security:
    providers:
        sse_icss_hybrid_user_provider:
            id: sse.icss.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        sso:
            pattern: ~
            anonymous: ~
            stateless: false
            simple_preauth:
                authenticator: sse.icss.authenticator
            provider: sse_icss_hybrid_user_provider

    access_control:
        - { path: ^/console, roles: ROLE_DASHBOARD_ACCESS }

    role_hierarchy:
        ROLE_DASHBOARD_ACCESS:
            - ROLE_SONATA_ADMIN
        ROLE_DASHBOARD_COMPANY_READ:
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_LIST
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_VIEW
        ROLE_DASHBOARD_COMPANY_FULL:
            - ROLE_DASHBOARD_COMPANY_READ
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_EXPORT
        ROLE_DASHBOARD_COMPANYCLASS_READ:
            - ROLE_SSE_ICSS_DASHBOARD_COMPANYCLASS_LIST
            - ROLE_SSE_ICSS_DASHBOARD_COMPANYCLASS_VIEW
        ROLE_DASHBOARD_COMPANYCLASS_FULL:
            - ROLE_DASHBOARD_COMPANYCLASS_READ
            - ROLE_SSE_ICSS_DASHBOARD_COMPANYCLASS_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_COMPANYCLASS_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_COMPANYCLASS_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_COMPANYCLASS_EXPORT
        ROLE_DASHBOARD_DIRECTION_READ:
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_LIST
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_VIEW
        ROLE_DASHBOARD_DIRECTION_FULL:
            - ROLE_DASHBOARD_DIRECTION_READ
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_EXPORT
        ROLE_DASHBOARD_INTERNTYPE_READ:
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_LIST
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_VIEW
        ROLE_DASHBOARD_INTERNTYPE_FULL:
            - ROLE_DASHBOARD_INTERNTYPE_READ
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_EXPORT
        ROLE_DASHBOARD_ARCHIVETYPE_READ:
            - ROLE_SSE_ICSS_DASHBOARD_ARCHIVETYPE_LIST
            - ROLE_SSE_ICSS_DASHBOARD_ARCHIVETYPE_VIEW
        ROLE_DASHBOARD_ARCHIVETYPE_FULL:
            - ROLE_DASHBOARD_ARCHIVETYPE_READ
            - ROLE_SSE_ICSS_DASHBOARD_ARCHIVETYPE_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_ARCHIVETYPE_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_ARCHIVETYPE_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_ARCHIVETYPE_EXPORT
        ROLE_DASHBOARD_PROJECT_READ:
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_LIST
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_VIEW
        ROLE_DASHBOARD_PROJECT_FULL:
            - ROLE_DASHBOARD_PROJECT_READ
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_EXPORT
        ROLE_DASHBOARD_STUDENT_READ:
            - ROLE_SSE_ICSS_DASHBOARD_STUDENT_LIST
            - ROLE_SSE_ICSS_DASHBOARD_STUDENT_VIEW
        ROLE_DASHBOARD_STUDENT_FULL:
            - ROLE_DASHBOARD_STUDENT_READ
            - ROLE_SSE_ICSS_DASHBOARD_STUDENT_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_STUDENT_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_STUDENT_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_STUDENT_EXPORT
        ROLE_DASHBOARD_TEACHER_READ:
            - ROLE_SSE_ICSS_DASHBOARD_TEACHER_LIST
            - ROLE_SSE_ICSS_DASHBOARD_TEACHER_VIEW
        ROLE_DASHBOARD_TEACHER_FULL:
            - ROLE_DASHBOARD_TEACHER_READ
            - ROLE_SSE_ICSS_DASHBOARD_TEACHER_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_TEACHER_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_TEACHER_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_TEACHER_EXPORT
        ROLE_DASHBOARD_USER_READ:
            - ROLE_SSE_ICSS_DASHBOARD_USER_LIST
            - ROLE_SSE_ICSS_DASHBOARD_USER_VIEW
        ROLE_DASHBOARD_USER_FULL:
            - ROLE_DASHBOARD_USER_READ
            - ROLE_SSE_ICSS_DASHBOARD_USER_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_USER_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_USER_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_USER_EXPORT
        ROLE_TEACHER:
            - ROLE_DASHBOARD_ACCESS
            - ROLE_LOGGED_IN
            - ROLE_SSE_ICSS_DASHBOARD_STUDENT_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_STUDENT_LIST
            - ROLE_SSE_ICSS_DASHBOARD_STUDENT_VIEW
        ROLE_STUDENT:
            - ROLE_DASHBOARD_ACCESS
            - ROLE_LOGGED_IN
        ROLE_USER:
            - ROLE_DASHBOARD_ACCESS
            - ROLE_LOGGED_IN
        ROLE_ADMIN:
            - ROLE_DASHBOARD_COMPANY_FULL
            - ROLE_DASHBOARD_COMPANYCLASS_FULL
            - ROLE_DASHBOARD_DIRECTION_FULL
            - ROLE_DASHBOARD_INTERNTYPE_FULL
            - ROLE_DASHBOARD_ARCHIVETYPE_FULL
            - ROLE_DASHBOARD_PROJECT_FULL
            - ROLE_DASHBOARD_STUDENT_FULL
            - ROLE_DASHBOARD_TEACHER_FULL
            - ROLE_DASHBOARD_USER_FULL