security:
    providers:
        sse_icss_hybrid_user_provider:
            id: sse.icss.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        sso:
            pattern: ~
            anonymous: ~
            stateless: false
            simple_preauth:
                authenticator: sse.icss.authenticator
            provider: sse_icss_hybrid_user_provider

    access_control:
        - { path: ^/console, roles: ROLE_DASHBOARD_ACCESS }

    role_hierarchy:
        ROLE_DASHBOARD_ACCESS:
            - ROLE_SONATA_ADMIN
        ROLE_DASHBOARD_COMPANY_READ:
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_LIST
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_VIEW
        ROLE_DASHBOARD_COMPANY_FULL:
            - ROLE_DASHBOARD_COMPANY_READ
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_COMPANY_EXPORT
        ROLE_DASHBOARD_DIRECTION_READ:
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_LIST
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_VIEW
        ROLE_DASHBOARD_DIRECTION_FULL:
            - ROLE_DASHBOARD_DIRECTION_READ
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_DIRECTION_EXPORT
        ROLE_DASHBOARD_INTERNTYPE_READ:
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_LIST
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_VIEW
        ROLE_DASHBOARD_INTERNTYPE_FULL:
            - ROLE_DASHBOARD_INTERNTYPE_READ
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_INTERNTYPE_EXPORT
        ROLE_DASHBOARD_PROJECT_READ:
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_LIST
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_VIEW
        ROLE_DASHBOARD_PROJECT_FULL:
            - ROLE_DASHBOARD_PROJECT_READ
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_CREATE
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_EDIT
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_DELETE
            - ROLE_SSE_ICSS_DASHBOARD_PROJECT_EXPORT
        ROLE_TEACHER:
            - ROLE_DASHBOARD_ACCESS
        ROLE_STUDENT:
            - ROLE_DASHBOARD_ACCESS
        ROLE_USER:
            - ROLE_DASHBOARD_ACCESS
        ROLE_ADMIN:
            - ROLE_DASHBOARD_COMPANY_FULL
            - ROLE_DASHBOARD_DIRECTION_FULL
            - ROLE_DASHBOARD_INTERNTYPE_FULL
            - ROLE_DASHBOARD_PROJECT_FULL