services:
    sse.icss.dashboard.companyclass:
        class: SSE\ICSSBundle\Admin\CompanyClassAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "param_management", label: "company_class" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\CompanyClass
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    sse.icss.dashboard.interntype:
        class: SSE\ICSSBundle\Admin\InternTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "param_management", label: "intern_type" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\InternType
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    sse.icss.dashboard.archivetype:
        class: SSE\ICSSBundle\Admin\ArchiveTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "param_management", label: "archive_type" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\ArchiveType
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    sse.icss.dashboard.project:
        class: SSE\ICSSBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "param_management", label: "param_project" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\Project
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    sse.icss.dashboard.direction:
        class: SSE\ICSSBundle\Admin\DirectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "param_management", label: "param_direction" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\Direction
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    sse.icss.dashboard.gender:
        class: SSE\ICSSBundle\Admin\GenderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "param_management", label: "param_gender" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\Gender
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    sse.icss.dashboard.company:
        class: SSE\ICSSBundle\Admin\CompanyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "recruit_management", label: "recruit_compnay" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\Company
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    sse.icss.dashboard.recruittype:
        class: SSE\ICSSBundle\Admin\RecruitTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "param_management", label: "recruit_type" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\RecruitType
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    sse.icss.dashboard.recruit:
        class: SSE\ICSSBundle\Admin\RecruitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "recruit_management", label: "recruit_info" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\Recruit
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    sse.icss.dashboard.student:
        class: SSE\ICSSBundle\Admin\StudentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "student_management", label: "student_info" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\Student
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]
            - [ setProjectListBuilder, [ @sse.icss.builder.project_list_builder ] ]
            - [ setGradeListBuilder, [ @sse.icss.builder.grade_list_builder ] ]
            - [ setDirectionListBuilder, [ @sse.icss.builder.direction_list_builder ] ]
            - [ setGenderListBuilder, [ @sse.icss.builder.gender_list_builder ] ]

    sse.icss.dashboard.teacher:
        class: SSE\ICSSBundle\Admin\TeacherAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "user_management", label: "teacher_info" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\Teacher
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

    # add mentor info
    sse.icss.dashboard.mentor:
        class: SSE\ICSSBundle\Admin\MentorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "user_management", label: "mentor_info" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\Teacher
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]
            - [ setSecurityContext, [@security.context] ]

    sse.icss.dashboard.user:
        class: SSE\ICSSBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "user_management", label: "user_info" }
        arguments:
            - ~
            - SSE\ICSSBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [SSEICSSBundle]]

