# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sse.icss.ssoservice:
        class: SSE\ICSSBundle\SSO\SSOService
        arguments: [ %SSEICSS.ssoApi% ]

    sse.icss.password_encoder:
        class: SSE\ICSSBundle\Security\User\PasswordEncoder

    sse.icss.user_provider:
        class: SSE\ICSSBundle\Security\User\HybridUserProvider
        arguments: [ @sse.icss.ssoservice, @doctrine.orm.entity_manager, @sse.icss.password_encoder ]

    sse.icss.recruit_service:
        class: SSE\ICSSBundle\DependencyInjection\RecruitService
        calls:
            - [setEntityManager, [ @doctrine.orm.entity_manager ]]

    sse.icss.company_service:
        class: SSE\ICSSBundle\DependencyInjection\CompanyService
        calls:
            - [setEntityManager, [ @doctrine.orm.entity_manager ]]

    sse.icss.authenticator:
        class: SSE\ICSSBundle\Security\User\HybridAuthenticator
        arguments: [ @security.http_utils ]
        public: false

    sse.icss.dynamic_content_marker:
        class: SSE\ICSSBundle\DependencyInjection\DynamicContentMarker
        calls:
            - [setRequest, [@request_stack]]

    sse.icss.builder.project_list_builder:
        class: SSE\ICSSBundle\Builder\ProjectListBuilder
        arguments: [ @doctrine.orm.entity_manager ]

    sse.icss.builder.direction_list_builder:
        class: SSE\ICSSBundle\Builder\DirectionListBuilder
        arguments: [ @doctrine.orm.entity_manager ]

    sse.icss.builder.gender_list_builder:
        class: SSE\ICSSBundle\Builder\GenderListBuilder
        arguments: [ @doctrine.orm.entity_manager ]

    sse.icss.builder.grade_list_builder:
        class: SSE\ICSSBundle\Builder\GradeListBuilder
        arguments: [ @doctrine.orm.entity_manager ]