# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sse.icss.ssoservice:
        class: SSE\ICSSBundle\SSO\SSOService
        arguments: [ %SSEICSS.ssoApi% ]

    sse.icss.password_encoder:
        class: SSE\ICSSBundle\Security\User\PasswordEncoder

    sse.icss.user_provider:
        class: SSE\ICSSBundle\Security\User\HybridUserProvider
        arguments: [ @sse.icss.ssoservice, @doctrine.orm.entity_manager, @sse.icss.password_encoder ]

    sse.icss.authenticator:
        class: SSE\ICSSBundle\Security\User\HybridAuthenticator
        arguments: [ @security.http_utils ]
        public: false